project:
  type: website

website:
  title: "Kimia Farma - VIX Talent Database"
  navbar:
    background: primary
    left:
      - href: bda.qmd
        text: Dashboard

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

